### ISSUE TITLE
ERROR: Cannot install requirements.txt and napalm because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by katsel** [SUNET/cnaas-nms#147]
`./integrationtests.sh` fails with an error while building the API container:

```
ERROR: Cannot install -r requirements.txt (line 12) and napalm==3.1.0 because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested napalm==3.1.0
    nornir 2.4.0 depends on napalm<3 and >=2
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
ERROR: Service 'cnaas_api' failed to build : The command '/bin/sh -c /opt/cnaas/cnaas-setup.sh $BUILDBRANCH' returned a non-zero code: 1
```

The error seems related to changes in the pip dependency resolver. See https://pip.pypa.io/en/latest/user_guide/#changes-to-the-pip-dependency-resolver-in-20-3-2020

A temporary fix is adding ` --use-deprecated=legacy-resolver` to the pip call.
A long-term seems to be updating `requirements.txt` with newer, compatible versions.

**Comment by indy-independence** [comment]
I'm working on the long-term solution of updating nornir to 3.0.0 in this branch feature.nornir_3

**Comment by indy-independence** [comment]
Nornir was upgraded to 3.0.0 in #148 so this should be fixed now
