### ISSUE TITLE
Don't stack trace when a device is unreachable

### ISSUE THREAD

**Issue by SpaceFarmer** [SUNET/cnaas-nms#172]
**Describe the bug**
When doing a dry-run to a group of switches and one of them is unreachable you get a long python stack trace in the NMS GUI.

**To Reproduce**
* Make one switch unreachable
* Perform a dry-run

**Expected behavior**
Instead of getting 50 lines of stack trace It would be preferable if it was handled with some kind of message saying the device could not be reached or something like that.

**Environment:**
CNaaS-NMS version: 1.2.1

**Comment by indy-independence** [comment]
@SpaceFarmer  I think this is an issue for the cnaas-front project right? https://github.com/SUNET/cnaas-front/issues
