### ISSUE TITLE
Case insensitive search in NMS

### ISSUE THREAD

**Issue by SpaceFarmer** [SUNET/cnaas-nms#173]
**Is your feature request related to a problem? Please describe.**
When copy pasting part of a switchname to search under "Devices", it is some times in capital letters and then i get no hit on my searh.

**Describe the solution you'd like**
It would be nice if the search was case insensitive instead.

**Additional context**

![image](https://user-images.githubusercontent.com/12208962/120644296-78192c00-c477-11eb-9211-80c832ca9e8d.png)

![image](https://user-images.githubusercontent.com/12208962/120644352-85ceb180-c477-11eb-8e72-6130b37e845f.png)

**Comment by indy-independence** [comment]
Fix merged in #175
