### ISSUE TITLE
Be able to sync only unsynchronized devices

### ISSUE THREAD

**Issue by SpaceFarmer** [SUNET/cnaas-nms#174]
**Is your feature request related to a problem? Please describe.**
From the dashboard view you can see the number of unsynchronized devices, but there is no way to sync only these devices.

**Describe the solution you'd like**
It would be nice if there was a way to synchronize just these devices without having to navigate to "groups" and then find a relevant group or groups to sync. Maybe there could be a "Sync" buttom next to the unsynchronized devices from the dashboard view.

**Additional context**

![image](https://user-images.githubusercontent.com/12208962/120801631-b2e79680-c541-11eb-917a-694c31c6a3be.png)

**Comment by indy-independence** [comment]
The default sync when you don't select a group or anything special is just "all unsynchronized devices"
