### ISSUE TITLE
Upgrade python3.7 -> 3.11

### ISSUE THREAD

**Issue by indy-independence** [SUNET/cnaas-nms#332]
NAPALM -> pyez -> ncclient dependency chain seems to support python ~~3.12~~ 3.11 since recently
https://github.com/napalm-automation/napalm/issues/2020
https://github.com/Juniper/py-junos-eznc/issues/1276

**Comment by Josephine-Rutten** [comment]
NAPALM does still need to do a new release. If this is done the 2nd of January, I try 3.12. If it takes longer, we will focus on 3.11. For now 3.11 seems to no problems and only some new packages.

**Comment by Josephine-Rutten** [comment]
Solved by merge of the pullrequest: https://github.com/SUNET/cnaas-nms/pull/334
